os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.2
env:
    global:
        - IS_TRAVIS=true
    matrix:
        - SWIFT_VERSION=3.0.2 BUILDTYPE=swiftbuild
        - SWIFT_VERSION=3.0.1  BUILDTYPE=swiftbuild
        - BUILDTYPE=xcrun
matrix:
    exclude:
        env: BUILDTYPE=xcrun
        os: linux

script:
  - ./Scripts/Apollo.sh
